"""Hierarchical model of MountainCar.

Macro states are generated by clustering the successor matrix.
No neural networks are used for the macro actions.
A smoother version of hierarchy with respect to episodes is implemented.
When running multiple trials for different episode counts, training continues
the same run (doesn't restart from zero).
Clusters are also ordered to stabilize the higher-level successor matrix.
"""
import warnings

warnings.simplefilter(action="ignore", category=FutureWarning)

# Standard library
import argparse
from collections import Counter, defaultdict
from copy import deepcopy
import glob
import os
import random
import sys
import time

# Third-party
import gymnasium as gym
import imageio
import matplotlib.animation as animation
import matplotlib.patches as mpatches
import matplotlib.pyplot as plt
import numpy as np
import torch
import torch.nn.functional as F
from matplotlib.cm import get_cmap
from matplotlib.collections import LineCollection
from matplotlib.colors import LogNorm
from sklearn.cluster import KMeans, SpectralClustering
from sklearn.manifold import SpectralEmbedding
from torch import nn
from torch.distributions import Categorical

from PIL import Image, ImageDraw
import matplotlib.cm as cm

# Local
from utils_mcar import (
    clamp,
    create_C,
    idx_to_loc,
    idx_to_onehot,
    loc_to_idx,
    micro_to_macro,
    onehot_to_idx,
    onehot_to_loc,
)

# np.set_printoptions(threshold=sys.maxsize, legacy="1.25")

class SR_Agent_Hierarchy(object):
    def __init__(self, env, A=None,B=None,C=None, gamma=0.99, alpha =0.1, inverse_factor=1, n_clust = 4, 
                 n_pos_bins=10, n_vel_bins=10, init_state=None, goal_loc = None, num_episodes=None, learn_likelihood = False, flat_vs_hierarchical='hierarchical'):
        self.env = env
        self.B = B
        self.B_macro = None
        self.M = None
            
        self.n_pos_bins = n_pos_bins
        self.n_vel_bins = n_vel_bins
        self.N = (n_pos_bins * n_vel_bins)

        self.C_macro = None
        self.gamma = gamma
        self.inverse_factor = inverse_factor
        
        # self.env.get_image(self.init_loc, goal_loc)
        self.s = None
        self.s_array = None
        self.a_array = None
        self.learn_likelihood = learn_likelihood
        self.n_clust = n_clust
        self.n_actions = self.env.action_space.n
        self.n_macro_actions = None
        
        if num_episodes is None:
            self.num_episodes = 0 # Keep track of number of episodes
        else:
            self.num_episodes = num_episodes
        self.learning_rate = alpha
        # self.learn_env_likelihood()
        self.low  = self.env.observation_space.low
        self.high = self.env.observation_space.high
        self.pos_space, self.vel_space, self.pos_space_regular, self.vel_space_regular = self.create_bins()
        self.init_state = init_state
        self.goal_loc = goal_loc
        self.flat_vs_hierarchical = flat_vs_hierarchical

        self.goal_states = self.get_goal_states(self.goal_loc)
        print("Goal states:", self.goal_states)
        self.C = create_C(self.goal_states, self.N, reward=10)
        # print("Goal prior C:", self.C)

    # Discretization helpers
    def create_bins(self):
        pos_space = np.concatenate([
            np.linspace(self.low[0], 0.5, self.n_pos_bins),
            [self.high[0]]
        ]) # Ensure reward consistency for last interval
        vel_space = np.linspace(self.low[1], self.high[1], self.n_vel_bins+1)
        pos_space_regular = np.linspace(self.low[0], self.high[0], self.n_pos_bins+1)
        vel_space_regular = vel_space
        print('Pos Edges', pos_space)
        print('Vel Edges', vel_space)
        return pos_space, vel_space, pos_space_regular, vel_space_regular

    def discretize_state(self, obs):
        pos, vel = obs
        # Clamp for edge cases in bins
        i = clamp(np.digitize(pos, self.pos_space), 1, self.n_pos_bins) - 1
        j = clamp(np.digitize(vel, self.vel_space), 1, self.n_vel_bins) - 1
        return (i, j)

    def get_state_index(self, state):
        return loc_to_idx(state, self.n_vel_bins)

    def get_goal_states(self, goal):
        """
        Returns list of goal states given a goal specification.
        goal: None (default goal at max position), int (position only), or list/array (position, velocity)
        reward: Reward value at goal states
        """
        if goal is None:
            pos = self.n_pos_bins - 1
            vel = None
        elif isinstance(goal, float) or isinstance(goal, int):
            pos = self.discretize_state((goal, 0))[0]
            vel = None
        elif isinstance(goal, (list, np.ndarray)) and len(goal) == 2:
            pos, vel = self.discretize_state(goal)
        else:
            raise ValueError("Invalid goal specification")
        if vel is not None:
            goal_states = [self.get_state_index((pos, vel))]
        else:
            goal_states = [self.get_state_index((pos, j)) for j in range(self.n_vel_bins)]
        return goal_states
    
    def get_observation(self, state_index):
        return idx_to_loc(state_index, self.n_vel_bins)

    def view_matrices(self):
        if self.learn_likelihood:
            learn_str = 'estimated'
        else:
            learn_str = 'actual'
        B_avg = np.sum(self.B, axis=2) / self.B.shape[-1]
        plt.figure()
        plt.title("Default Policy B Matrix",fontsize=20)
        plt.imshow(B_avg)#, norm=LogNorm(vmin=B_avg.min(), vmax=B_avg.max()))
        plt.xticks(list(range(0,self.env.grid_size**2)),fontsize=12)
        plt.yticks(list(range(0, self.env.grid_size**2)),fontsize=12)
        plt.savefig(f"figures/matrices/B_matrix_micro.png", format="png")
        plt.close()

        plt.figure()
        plt.imshow(self.M, aspect='equal', cmap='cividis')#, norm=LogNorm(vmin=self.M.min(), vmax=self.M.max()))
        plt.xticks(list(range(0,self.env.grid_size**2)),fontsize=12)
        plt.yticks(list(range(0,self.env.grid_size**2)),fontsize=12)
        plt.title(f"Successor Matrix M ({learn_str})", fontsize=20)
        plt.savefig(f"figures/matrices/m_{learn_str}_micro.png", format="png")
        plt.close()
        np.save("data/M.npy", self.M)
        
        B_macro_avg = np.sum(self.B_macro, axis=2) / self.n_macro_actions
        plt.figure()
        plt.title("Default Policy B Matrix",fontsize=20)
        plt.imshow(B_macro_avg)#, norm=LogNorm(vmin=B_avg.min(), vmax=B_avg.max()))
        plt.xticks(list(range(0,self.n_clust)),fontsize=12)
        plt.yticks(list(range(0, self.n_clust)),fontsize=12)
        for i in range(len(B_macro_avg)):
            for j in range(len(B_macro_avg)):
                plt.text(j, i, f'{B_macro_avg[i, j]:.2f}',
                            ha="center", va="center", color="w")
        plt.savefig(f"figures/matrices/B_matrix_macro.png", format="png")
        plt.close()

        plt.figure()
        plt.imshow(self.M_macro, aspect='equal', cmap='cividis')#, norm=LogNorm(vmin=self.M.min(), vmax=self.M.max()))
        plt.xticks(list(range(0,self.n_clust)),fontsize=12)
        plt.yticks(list(range(0,self.n_clust)),fontsize=12)
        plt.title(f"Successor Matrix M ({learn_str})", fontsize=20)
        for i in range(len(self.M_macro)):
            for j in range(len(self.M_macro)):
                plt.text(j, i, f'{self.M_macro[i, j]:.2f}',
                            ha="center", va="center", color="w")
        plt.savefig(f"figures/matrices/m_{learn_str}_macro.png", format="png")
        plt.close()
 
    
    def visualize_policy(self):
        
        # Clear out old images
        for filename in glob.glob("figures/Macro Action Network/Macro_Action_Network_*"):
            os.remove(filename) 

        grid_size = self.env.grid_size

        for macro_state in range(self.n_clust):
            for macro_action, macro_final_state in enumerate(self.adj_list[macro_state]):
                final_state = self.bottleneck_states[(macro_state, macro_final_state)][0]
                C = idx_to_onehot(final_state, grid_size)
                V = self.M @ C
                print(f'\nInitial state: Micro - {macro_state}')
                print(f'Final state: Micro - {final_state}, Macro - {macro_final_state}')
                arrows_grid = np.full((grid_size,grid_size),-1)
                for state in self.macro_state_list[macro_state]:
                    V_adj = []
                    for act in range(self.n_actions):
                        s_adj = self.B[:,:,act] @ idx_to_onehot(state, grid_size)
                        V_adj.append(V[onehot_to_idx(s_adj)])   
                    # ba_gen = (ele for ele in np.argsort(V_adj)[::-1])
                    best_action = np.argmax(V_adj)
                    arrows_grid[idx_to_loc(state,grid_size)] = best_action
                    
                arrows_grid = arrows_grid.T
                
                plt.figure()
                arrows = {1:(1,0), 0:(-1,0),3:(0,1),2:(0,-1)}
                scale = 0.25
        
                plt.xticks(np.arange(grid_size),fontsize=12)
                plt.yticks(np.arange(grid_size),fontsize=12)
                fig, ax = plt.subplots(figsize=(grid_size,grid_size))
                for r, row in enumerate(arrows_grid):
                    for c, cell in enumerate(row):
                        if cell in arrows:
                            plt.arrow(c-scale*arrows[cell][0], r-scale*arrows[cell][1], scale*arrows[cell][0], scale*arrows[cell][1], head_width=0.15,color='w')
                im = plt.imshow(self.lg,cmap='gist_heat')
                colours = im.cmap(im.norm(np.unique(self.lg)))
                
                #Just to add labels for the macro actions in the figure
                patches = [ mpatches.Patch(color=colours[i], label=f'{i}' ) for i in range(len(colours)-1) ]
                plt.legend(handles=patches, bbox_to_anchor=(1.05, 1), loc=2, borderaxespad=0.)
                plt.title(f"Macro Action Policy from state {macro_state} to {macro_final_state}", fontsize=20)
                plt.savefig(f"figures/Macro Action Network/Macro_Action_Network_{macro_state}_{macro_final_state}.png", format="png")
                plt.tight_layout()
                plt.close()


    def update_sr(self, current_exp, next_exp, M):
        # SARSA TD learning rule
        # Modifies M
        s_1 = current_exp[0]
        s_2 = current_exp[2]
        r = current_exp[3]
        done = current_exp[4]
        I = idx_to_onehot(s_2, self.N)
        if done:            
            td_error = (I + self.gamma * idx_to_onehot(s_2, self.N) - M[s_1,:])
        else:
            td_error = (I + self.gamma * M[s_2, :] - M[s_1,:])
        M[s_1,:] += self.learning_rate * td_error
        return td_error


    def actual_successor_transition_matrix(self):
        env = self.env
        grid_size = self.env.grid_size

        self.B = env.get_transition_dist()
        I = np.identity(grid_size**2)
        B_avg = np.sum(self.B, axis=2) / self.n_actions
        self.M = np.linalg.inv(I - (0.95 * B_avg))
        return self.B, self.M
    

    def show_video(self):
        #print(self.s_array)
        gs = self.env.grid_size

        fig = plt.figure()
        grid = np.zeros((gs, gs))
        if len(self.env.walls) > 0:
            wall_idx = tuple(np.array(self.env.walls).T) # Convert  to right format
        start_idx = self.init_loc
        goal_idx = idx_to_loc(self.goal_idx, gs)
        grid[start_idx] = 1
        grid[goal_idx] = 0.5
        grid[wall_idx] = 0.25
        im = plt.imshow(grid.T, aspect='equal', cmap='magma')
        plt.title(f'Gridworld of size {gs}')
        
        ax = plt.gca()
        
        # Major ticks
        ax.set_xticks(np.arange(0, gs, 1))
        ax.set_yticks(np.arange(0, gs, 1))

        # Labels for major ticks
        ax.set_xticklabels(np.arange(gs, 1))
        ax.set_yticklabels(np.arange(gs, 1))

        # Minor ticks
        ax.set_xticks(np.arange(-.5, gs, 1), minor=True)
        ax.set_yticks(np.arange(-.5, gs, 1), minor=True)

        # Gridlines based on minor ticks
        ax.grid(which='minor', color='w', linestyle='-', linewidth=2)

        # Remove minor ticks
        ax.tick_params(which='minor', bottom=False, left=False)

        past_idx_array = []

        def init():
            grid = np.zeros((gs, gs))
            grid[wall_idx] = 0.25
            grid[start_idx] = 1
            grid[goal_idx] = 0.5
            im.set_data(grid)
            return im,


        def animate(i):
            for txt in ax.texts[::-1]:
                txt.remove()
            s = self.s_array[i]
            grid = np.zeros((gs, gs))
            grid[wall_idx] = 0.25
            s_idx = onehot_to_loc(s, gs)
            grid[s_idx] = 1
            grid[goal_idx] = 0.5
            
            # for past_idx in past_idx_array:
            #     grid[past_idx] = 0.01
            grid[s_idx] = 1
            past_idx_array.append(s_idx)
            im.set_data(grid.T)

            
            ax.text(s_idx[0], s_idx[1], 'Agent', fontsize = 10, ha="center", va="center", color="b")
            ax.text(goal_idx[0], goal_idx[1], 'Goal', fontsize = 10, ha="center", va="center", color="w")
            for idx in self.env.walls:
                ax.text(idx[0], idx[1], 'Wall', fontsize = 10, ha="center", va="center", color="w")
                
            if i > 0:
                ax.scatter(past_idx_array[i-1][0], past_idx_array[i-1][1], color='y')
            if i == len(self.s_array) - 2:
                plt.savefig(f'figures/trajectory.png')
            # ax.scatter(s_idx[0], s_idx[1], color='y')

            return im,
        ani = animation.FuncAnimation(fig, animate, np.arange(len(self.s_array)), init_func=init,
                              interval=500, blit=True)
        ani.save(f'videos/env_micro.mp4')
        plt.close()
         
        
    def env_reset(self,init=None, verbose=False):
        '''
        Resets the environment to a specific initial state or a random state within bounds.
        init: list or None
            If provided, should be a list [position, velocity] to set the initial state.
            If None, a random state within the environment's bounds is chosen.
        verbose: bool

            If True, prints the initialized state.
        Returns:
        init_state: list
            The initialized state [position, velocity].
        '''
        if init is None:
            init_state = np.random.uniform(self.low, self.high)    
        else:
             init_state = init   
        if verbose:
            print("Resetting environment with random state:", init_state)
        obs, _ = self.env.reset()
        self.env.unwrapped.state = init_state
        return init_state
    
    def learn_successor_transition_matrix(self, num_episodes):
        env = self.env
        N = self.N

        if self.M is None:
            self.B = np.zeros((N,N,self.n_actions))
            self.M = np.zeros((N,N))   

        experiences = []
        lifetime_td_errors = []

        for ep in range(1, num_episodes+1):
            print(f"Episode {ep}/{num_episodes}", end='\r')
            obs =  self.env_reset()
            s = self.discretize_state(obs)
            done = False
            total_reward = 0
            # steps = 0
            episodic_error = []
            while not done:
                action = random.randrange(self.n_actions)
                smooth_step = 5
                for i in range(smooth_step):
                    step = env.step(action)
                    if len(step) == 5:
                        obs_next, r, terminated, truncated, _ = step
                        done = terminated or truncated
                        # if terminated:
                        #     print("reward:", r)
                        #     print(step)
                    else:
                        obs_next, r, done, _ = step
                    s = self.discretize_state(obs)
                    s_next = self.discretize_state(obs_next)
                    
                    s_index = self.get_state_index(s)
                    s_next_index = self.get_state_index(s_next)

                    # print(f"Episode {ep}, Step {len(experiences)+1}, State {s} Observed {obs}, Action {action}, Next State {s_next}, Reward {r}, Done {done}")
                    if s_index != s_next_index or done:
                        # if s_next_index > self.N-self.n_vel_bins:
                        #     print(f"Reached terminal state {s_next_index} from {s_index}")
                        break
                self.B[s_next_index, s_index, action] += 1   # Update B
                experiences.append([s_index, action, s_next_index, r, done])
                obs = obs_next
                if r != -1:
                    print("Positive reward received:", r)
                total_reward += r
                # steps += 1
                if len(experiences) > 1:
                    td_sr = self.update_sr(experiences[-2], experiences[-1],self.M)
                    episodic_error.append(np.mean(np.abs(td_sr)))
                if done:
                    td_sr = self.update_sr(experiences[-1], experiences[-1],self.M)
                    episodic_error.append(np.mean(np.abs(td_sr)))
                    break
            lifetime_td_errors.append(np.mean(episodic_error))

        # Handling transitions not encountered by manually adding a P(s_t+1=a|s_t=a)=1
        for col in range(N):
            for action in range(self.n_actions):
                col_sum = np.sum(self.B[:,col,action])
                if col_sum == 0:
                    self.B[col,col,action] = 1
        # Normalize matrix
        self.B = self.B/self.B.sum(axis=0, keepdims=True)
        

        print('Learning Complete')
        start_state = [-0.5, 0]
        M_orig_idx = self.get_state_index(self.discretize_state(start_state))
        M_orig = self.M[M_orig_idx, :].reshape(self.n_pos_bins, self.n_vel_bins) + 1e-5
        plt.figure()

        plt.imshow(
            M_orig,
            aspect='auto',
            cmap='copper',
            norm=LogNorm(vmax=M_orig.max()),
            extent=[self.vel_space[0], self.vel_space[-1], self.pos_space[0], self.pos_space[-1]],  # limits
            origin="lower"
        )
        plt.xticks(
            ticks=self.vel_space,
            labels=np.round(self.vel_space, 3), 
            fontsize=12
        )
        plt.yticks(
            ticks=np.linspace(self.low[0], self.high[0], self.n_pos_bins+1), # Since pos_space has 0.5 extra element
            labels=np.round(self.pos_space, 3), 
            fontsize=12
        )
        plt.xlabel("Velocity", fontsize=12)
        plt.ylabel("Position", fontsize=12)
        plt.title(f"Successor Matrix M from start {start_state}", fontsize=20)
        plt.colorbar(label="Value")
        plt.savefig(f"figures/matrices/m_mcar.png", format="png")
        plt.close()
        return self.B, self.M
    
    def learn_successor_transition_matrix_macro(self):
        NC = self.n_clust
        action_list = self.adj_list
        A = self.n_macro_actions   
        B = np.zeros((NC,NC,A))
        M = np.zeros((NC,NC))

        for state in range(NC):
            if state not in action_list:
                B[state,state,0] += 1
                continue
            for ind,val in enumerate(action_list[state]):
                B[val,state,ind] += 1
                
        I = np.eye(NC)

        # Handling transitions not encountered by manually adding a P(s_t+1=a|s_t=a)=1
        for col in range(NC):
            for action in range(A):
                col_sum = np.sum(B[:,col,action])
                if col_sum == 0:
                    B[col,col,action] = 1
        # Normalize matrix
        B = B/B.sum(axis=0, keepdims=True)
        B_avg = np.sum(B, axis=2)
        B_avg = B_avg/np.sum(B_avg, axis=1)[:,np.newaxis] 
        M = np.linalg.pinv(I - (0.9 * B_avg))
        return B, M
    
    
    def learn_macro_clusters(self):
        N = self.N
        
        Mf = np.maximum(self.M, self.M.transpose()) # To fix symmetry issues
 
        MANUAL_CLUSTERING = manually_set_macro_states

        if not MANUAL_CLUSTERING:
            print("Learning clusters using spectral clustering")   
            emb = SpectralEmbedding(n_components=2, affinity='precomputed').fit_transform(Mf)
            
            # K-means clustering
            # kmeans = KMeans(n_clusters=self.n_clust, n_init=100)
            # labels = kmeans.fit_predict(emb)

            labels = np.ones(N) * self.n_clust  
            sc = SpectralClustering(self.n_clust, affinity='precomputed', n_init=100,
                            assign_labels='discretize')
            labels = sc.fit_predict(Mf)
            # Ensure all the goal states are in the last cluster
            # labels[-self.n_vel_bins:] = self.n_clust-1
            labels_grid = labels.reshape(self.n_pos_bins, self.n_vel_bins)
        
        else:
            print("Using manual clustering")
            # Manually set clusters for more interpretable results
            # 
            labels_grid = np.zeros((self.n_pos_bins, self.n_vel_bins))
            # for pos in range(self.n_pos_bins):
            #     for vel in range(self.n_vel_bins):
            #         if vel < self.n_vel_bins // 2:
            #             labels_grid[pos, vel] = pos
            #         elif vel >= self.n_vel_bins // 2 and vel < self.n_vel_bins * 3 // 4:
            #             labels_grid[pos, vel] = (self.n_vel_bins + pos)
            #         else:
            #             labels_grid[pos, vel] = (self.n_vel_bins * 2 + pos)

            cluster_centroids = [[-0.5, 0], [-0.26, 0], [-0.88, 0]]
            for i, centroid in enumerate(cluster_centroids):
                pos_cen, vel_cen = centroid
                idx = self.discretize_state(centroid)
                labels_grid[idx[0], idx[1]] = i+1
                # a box around centroid also is included in cluster
                # labels_grid[idx[0], idx[1]-1:idx[1]+1] = i+1

            labels_grid[-1,:] = len(cluster_centroids)+1  # Goal state cluster
            # for pos in range(self.n_pos_bins):
            #     for vel in range(self.n_vel_bins):
            #         if pos in [2,3] and vel in [2,3]:
            #             labels_grid[pos, vel] = 0
            #         elif pos <=4 and pos>=1 and vel <=4 and vel>=1:
            #             labels_grid[pos, vel] = 1
            #         elif pos == 0 and vel in [2,3]:
            #             labels_grid[pos, vel] = 1
            #         elif pos in [6,7] and vel < 4:
            #             labels_grid[pos, vel] = 2
            #         elif pos in [6,7] and vel >= 4:
            #             labels_grid[pos, vel] = 3
            #         elif vel > 3:
            #             labels_grid[pos, vel] = 4
            #         else:
            #             labels_grid[pos, vel] = 5
            labels = labels_grid.flatten()
        

        unique_labels = set(labels)
        mapping = {old_label: new_label for new_label, old_label in enumerate(sorted(unique_labels))}
        labels = np.array([mapping[label] for label in labels])
        self.n_clust = len(unique_labels)
        print(self.n_clust, labels)

        self.lg = labels_grid
        # Last cluster is set of walls which isn't added to state list s in the end
        counts = Counter(labels)
        R = defaultdict(list)
        for i,n in enumerate(labels):
            R[n].append(i)
        s = [R[i] for i in range(self.n_clust)] 
        print(s)
        
        inv_s = {}
        for k, seq in enumerate(s):
            for idx in seq:
                inv_s[idx] = k
        print('Clustering complete')

    
        plt.figure()
        im = plt.imshow(
            labels_grid.T,
            aspect='auto',
            extent=[self.pos_space[0], self.pos_space[-1], self.vel_space[0], self.vel_space[-1]],  # limits
            origin="lower"
        )
        colours = im.cmap(im.norm(np.unique(labels_grid))) 
        plt.xticks(
            ticks=self.pos_space_regular,
            labels=np.round(self.pos_space, 3), 
            fontsize=12
        )
        
        plt.yticks(
            ticks=self.vel_space_regular,
            labels=np.round(self.vel_space, 3), 
            fontsize=12
        )

        plt.xlabel("Position", fontsize=12)
        plt.ylabel("Velocity", fontsize=12)
        patches = [ mpatches.Patch(color=colours[i], label=f'{i}' ) for i in range(len(colours)) ]
        plt.legend(handles=patches)
        plt.title(f"Macro state clusters", fontsize=20)
        plt.savefig(f"figures/clustering/Macro_s_mc.png", format="png")
        plt.close()


            
        if not MANUAL_CLUSTERING:    
            plt.figure()
            for i, lst in enumerate(s):
                plt.scatter(emb[lst,0], emb[lst,1], label=f'{i}',color=colours[i], s=75)
            plt.legend()
            plt.title('Micro states clusters')
            plt.savefig('figures/clustering/macro_state_viz_mc.png')
            plt.close()

        return s, inv_s

    def learn_macro_clusters_position(self):
        self.n_clust=self.n_clust//2
        Mf = np.maximum(self.M, self.M.transpose()) # To fix symmetry issues
        Mf = np.sum(Mf.reshape(self.n_pos_bins, self.n_vel_bins, self.n_pos_bins, self.n_vel_bins), axis=(1,3))

        N = self.n_pos_bins
        emb = SpectralEmbedding(n_components=2, affinity='precomputed').fit_transform(Mf)
        labels = np.ones(N) * self.n_clust  
        sc = SpectralClustering(self.n_clust, affinity='precomputed', n_init=100,
                        assign_labels='discretize')
        labels = sc.fit_predict(Mf)
        print(labels)
        labels_grid = labels.reshape(self.n_pos_bins, 1)
        # Copy along velocity
        labels_grid = np.tile(labels_grid, (1, self.n_vel_bins))
        labels = labels_grid.flatten()

        counts = Counter(labels)
        R = defaultdict(list)
        for i,n in enumerate(labels):
            R[n].append(i)
        s = [R[i] for i in range(self.n_clust)] 
        print(s)
        
        inv_s = {}
        for k, seq in enumerate(s):
            for idx in seq:
                inv_s[idx] = k
        print('Clustering complete')

        
        plt.figure()
        im = plt.imshow(
            labels_grid.T,
            aspect='auto',
            extent=[self.pos_space[0], self.pos_space[-1], self.vel_space[0], self.vel_space[-1]],  # limits
            origin="lower"
        )
        colours = im.cmap(im.norm(np.unique(labels_grid))) 
        plt.xticks(
            ticks=self.pos_space_regular,
            labels=np.round(self.pos_space, 3), 
            fontsize=12
        )
        
        plt.yticks(
            ticks=self.vel_space_regular,
            labels=np.round(self.vel_space, 3), 
            fontsize=12
        )

        plt.xlabel("Position", fontsize=12)
        plt.ylabel("Velocity", fontsize=12)
        patches = [ mpatches.Patch(color=colours[i], label=f'{i}' ) for i in range(len(colours)) ]
        plt.legend(handles=patches)
        plt.title(f"Macro state clusters", fontsize=20)
        plt.savefig(f"figures/clustering/Macro_s_mc.png", format="png")
        plt.close()
             
        emb = emb.reshape(self.n_pos_bins, 1, 2)
        emb = np.tile(emb, (1, self.n_vel_bins, 1))  # Copy along velocity
        emb = emb.reshape(N * self.n_vel_bins, 2)

        plt.figure()
        for i, lst in enumerate(s):
            plt.scatter(emb[lst,0], emb[lst,1], label=f'{i}',color=colours[i], s=75)
        plt.legend()
        plt.title('Micro states clusters')
        plt.savefig('figures/clustering/macro_state_viz_mc.png')
        plt.close()

        return s, inv_s
 
    def learn_adjacency(self, num_episodes):
        env = self.env
        N = self.N

        train_episode_length = 40
        experiences = []
        lifetime_td_errors = []

        adj_list = defaultdict(set)
        bottleneck_states = defaultdict(set)

        MANUAL_ADJ = manually_set_macro_states
        FLATTEN_VELOCITY = False
        if not MANUAL_ADJ:
            # Learn which macro states are adjacent, and also improver M further using the new info we have
            for ep in range(1, num_episodes+1):
                print(f"Episode {ep}/{num_episodes}", end='\r')
                obs =  self.env_reset()
                s = self.discretize_state(obs)
                done = False
                total_reward = 0
                # steps = 0
                episodic_error = []
                while not done:
                    action = random.randrange(self.n_actions)
                    smooth_step = 10
                    for i in range(smooth_step):
                        step = env.step(action)
                        if len(step) == 5:
                            obs_next, r, terminated, truncated, _ = step
                            done = terminated or truncated
                        else:
                            obs_next, r, done, _ = step
                        s = self.discretize_state(obs)
                        s_next = self.discretize_state(obs_next)
                        
                        s_index = self.get_state_index(s)
                        s_next_index = self.get_state_index(s_next)

                        if s_index != s_next_index:
                            break
                    experiences.append([s_index, action, s_next_index, r, done])
                    s_macro = self.micro_to_macro[s_index]
                    s_next_macro = self.micro_to_macro[s_next_index]
                    if s_macro != s_next_macro:
                        adj_list[s_macro].add(s_next_macro)
                        bottleneck_states[(s_macro,s_next_macro)].add(s_next_index)
                    obs = obs_next

                    if self.learn_likelihood:
                        if len(experiences) > 1:
                            td_sr = self.update_sr(experiences[-2], experiences[-1],self.M)
                            episodic_error.append(np.mean(np.abs(td_sr)))
                        if done:
                            td_sr = self.update_sr(experiences[-1], experiences[-1],self.M)
                            episodic_error.append(np.mean(np.abs(td_sr)))
                            break
                if self.learn_likelihood:
                    lifetime_td_errors.append(np.mean(episodic_error))
            bottleneck_states = {k:list(v) for k,v in bottleneck_states.items()}
            adj_list = {k:list(v) for k,v in adj_list.items()}
        else:
            print("Using manual adjacency")
            adj_list = {0:[0], 1:[2], 2:[1,3], 3:[2,4], 4:[3]}  # Manually set for interpretability
            cluster_centroids = [[0,-0.07],[-0.5, 0], [-0.26, 0], [-0.88, 0], [0.51, 0.02]]
            cluster_inds = [self.get_state_index(self.discretize_state(centroid)) for centroid in cluster_centroids]
            print('Cluster Indices:', cluster_inds)
            for k,v in adj_list.items():
                for j in v:
                    bottleneck_states[(k,j)].add(cluster_inds[j])
            bottleneck_states = {k:list(v) for k,v in bottleneck_states.items()}
     
        print('Adjacency learning complete')
        self.n_macro_actions = max(len(v) for k,v in adj_list.items())            
        return adj_list, bottleneck_states
        
    def execute_macro_action(self, init_state, final_state):
        env = self.env
        N = self.N
        
        #for bottleneck_state in self.bottleneck_states[(init_state, final_state)]: break# Obtain element from set of size 1
        bottleneck_states = self.bottleneck_states[(init_state, final_state)]
        # C = create_C(self.goal_states, N, reward=10)
        C =  create_C(bottleneck_states, N, reward=0)
        V = self.M @ C
        done = False
        s_vec = idx_to_onehot(self.s, N)

        frames = []      # for mp4
        positions = []   # for trajectory plot
        velocities = []
        actions = []     # for trajectory plot

        end_states = (self.s in bottleneck_states) or (self.s in self.goal_states)
        # if end_states: done = True
         # If already in terminal state 
        while not done or end_states:
            V_adj = []
            # Get values of adjacent states
            for act in range(self.n_actions):
                s_adj = self.B[:,:,act] @ s_vec
                V_adj.append(V[onehot_to_idx(s_adj)])         
            ba_gen = (ele for ele in np.argsort(V_adj)[::-1])
            best_action = next(ba_gen)

            smooth_step = 10
            for i in range(smooth_step):
                # if i % (smooth_step // 2) == 0:
                #     try:
                #         best_action = next(ba_gen)
                #     except StopIteration:
                #         best_action = random.randrange(self.n_actions)

                step = self.env.step(best_action)
                obs_next, r, terminated, truncated, _ = step
                done = truncated or terminated
                
                s_next = self.discretize_state(obs_next)
                s_ind_next = self.get_state_index(s_next)
                self.s = s_ind_next
                s_vec_next = idx_to_onehot(s_ind_next, N)
                print('s:', s_next, 'obs:', obs_next, 'a:', best_action, 'r:', r, 'done:', done)
                obs, self.s, s_vec = obs_next, s_ind_next, s_vec_next

                frames.append(self.env.render())
                positions.append(obs[0])
                velocities.append(obs[1])
                actions.append(best_action)
                if done:  break
                end_states = (self.s in bottleneck_states) or (self.s in self.goal_states)
                if end_states: break
            macro_state = self.micro_to_macro[self.s]
            if macro_state == final_state:
                print(f"Reached final state {final_state} from {init_state}")
                break
            # elif macro_state != init_state:
            #     print(f"Macro state changed to {macro_state} during execution of macro action from {init_state} to {final_state}")
            #     break
        return frames, positions, velocities, actions, done

    def learn_env_likelihood(self, num_episodes=None):
        if num_episodes is None:
            num_episodes = 500
        self.num_episodes += num_episodes
        if self.learn_likelihood:
            self.B, self.M = self.learn_successor_transition_matrix(num_episodes - num_episodes//self.n_actions)
            np.save("data/B.npy", self.B)
            np.save("data/M.npy", self.M)
            
        else:
            self.B = np.load("data/B.npy")
            self.M = np.load("data/M.npy")
            print("Loaded B and M from files")
        if self.flat_vs_hierarchical == 'hierarchical':
            self.macro_state_list, self.micro_to_macro = self.learn_macro_clusters_position()
        # print(self.macro_state_list, self.micro_to_macro)
        
            # Create C macro now that we have macro states
            self.C_macro = np.zeros(self.n_clust)
            for i in range(self.n_clust):
                self.C_macro[i] = np.sum(self.C[self.macro_state_list[i]])
            print('C_macro',self.C_macro)
            self.adj_list, self.bottleneck_states = self.learn_adjacency(num_episodes//self.n_actions)
            print('adj', self.adj_list)
            print('bs',self.bottleneck_states)
            self.B_macro, self.M_macro =  self.learn_successor_transition_matrix_macro()

    def run_episode_flat(self, time_episode = True, reset_init = True):
        if time_episode == True:
            start_time = time.time()
        if reset_init:
            obs = self.env_reset(init=self.init_state, verbose=True)
            s = self.discretize_state(obs)
            self.s = self.get_state_index(s)
        done = False

        frames = []      # for mp4
        positions = []   # for trajectory plot
        velocities = []
        actions = []     # for trajectory plot
        # print(self.M, self.C)
        V = self.M @ self.C

        s_vec = idx_to_onehot(self.s, self.N)
        # s_arr = []
        
        while not done:
            V_adj = []
            for act in range(self.n_actions):
                s_adj = self.B[:,:,act] @ s_vec
                V_adj.append(V[onehot_to_idx(s_adj)])      
            ba_gen = (ele for ele in np.argsort(V_adj)[::-1])
            best_action = next(ba_gen)
            print(V_adj)
            smooth_step = 10
            for i in range(smooth_step):
                
                #    break
                # if i % (smooth_step // 2) == 0:
                #     try:
                #         best_action = next(ba_gen)
                #     except StopIteration:
                #         best_action = random.randrange(self.n_actions)

                step = self.env.step(best_action)
                obs_next, r, terminated, truncated, _ = step
                # if self.goal_loc is not None:
                #     if np.abs(self.s - self.goal_loc) < 0.1: terminated = True
                if self.s in self.goal_states: terminated = True
                done = terminated or truncated
                
                s_next = self.discretize_state(obs_next)
                s_ind_next = self.get_state_index(s_next)

                s_vec_next = idx_to_onehot(s_ind_next, self.N)
                # s_arr.append(s_next)
                print('s:', s_next, 'obs:', obs_next, 'a:', best_action, 'r:', r, 'done:', done)
                obs, s, self.s, s_vec = obs_next, s_next, s_ind_next, s_vec_next

                frames.append(self.env.render())
                positions.append(obs[0])
                velocities.append(obs[1])
                actions.append(best_action)
                # print('r:',r)
                # print('done',done)

                if s_ind_next != self.s or done:  break
            # print('s:', s, 'obs:', obs_next)

        time_elapsed = 0
        if time_episode == True:
            end_time = time.time()
            time_elapsed = end_time - start_time
            print(f"Episode finished in {time_elapsed} seconds")
        return frames, positions, velocities, actions, V, time_elapsed

    def run_episode_hierarchical(self, time_episode = True):
        if time_episode == True:
            start_time = time.time()
        obs = self.env_reset(init=self.init_state, verbose=True)
        s = self.discretize_state(obs)
        self.s = self.get_state_index(s)
        done = False

        frames_all = []      # for mp4
        positions_all = []   # for trajectory plot
        velocities_all = []
        actions_all = []     # for trajectory plot

        self.s_macro = self.micro_to_macro[self.s]
        s_macro_max = np.unique([self.micro_to_macro[x] for x in self.goal_states])
        print('s_macro', self.s_macro, 's_macro_max', s_macro_max)
        V_macro = self.M_macro @ self.C_macro

        s_vec = idx_to_onehot(self.s, self.N)

        if time_episode == True:
            ckpt_time = time.time()
            
        limit_steps = args.test_steps * 0.5
        step_count = 0
        
        while self.s_macro not in s_macro_max and not done:
            s_macro = self.micro_to_macro[self.s]
            V_adj_macro = []
            for macro_act in range(self.n_macro_actions):
                if s_macro in self.adj_list and macro_act < len(self.adj_list[s_macro]):
                    s_adj_macro = self.B_macro[:,:,macro_act] @ idx_to_onehot(s_macro, self.n_clust)
                    V_adj_macro.append(V_macro[onehot_to_idx(s_adj_macro)])
                else:
                    V_adj_macro.append(-np.inf)  # Invalid action
            ba_gen_macro = (ele for ele in np.argsort(V_adj_macro)[::-1])
            try:
                best_macro_action = next(ba_gen_macro)
            except StopIteration:
                print("No valid macro actions available. Ending episode.")
                break
            if s_macro not in self.adj_list or best_macro_action >= len(self.adj_list[s_macro]):
                print(f"Selected macro action {best_macro_action} is invalid. Ending episode.")
                break
            final_macro_state = self.adj_list[s_macro][best_macro_action]
            print(f"Current macro state: {s_macro}, Executing macro action to: {final_macro_state}")
            frames, positions, velocities, actions, done = self.execute_macro_action(s_macro, final_macro_state)

            self.s_macro = self.micro_to_macro[self.s]
            print(f"New state: {self.s}, New macro state: {self.s_macro}")
            step_count += len(actions)
            print("Step count:", step_count)

            s_vec = idx_to_onehot(self.s, self.N)

            if (self.s in self.goal_states) or step_count >= limit_steps:
                done = True

            frames_all.extend(frames)
            positions_all.extend(positions)
            velocities_all.extend(velocities)
            actions_all.extend(actions)
            print("Done", done)
        
        if time_episode == True:
            ckpt_time_2 = time.time()
            print(f"Hierarchical decision time: {ckpt_time_2 - ckpt_time:.2f} seconds")

        V = self.M @ self.C   
        print('Current state:', self.s, 'Macro state:', self.s_macro)
        if self.s_macro in s_macro_max:
            print("Reached terminal macro state.")
        else:
            print("Did not reach terminal macro state.")

        # Getting to final terminal state if not already there
        if self.s not in self.goal_states:
            print("Executing flat policy to reach terminal state.")
            frames, positions, velocities, actions, _, _ = self.run_episode_flat(time_episode=True, reset_init=False)
            frames_all.extend(frames)
            positions_all.extend(positions)
            velocities_all.extend(velocities)
            actions_all.extend(actions)

        if time_episode == True:
            end_time = time.time()
            time_elapsed = (end_time - ckpt_time_2) + (ckpt_time - start_time)
            print(f"Total episode time: {time_elapsed} seconds")
        return frames_all, positions_all, velocities_all, actions_all, V, time_elapsed

    def _mc_world_to_screen(self, pos, screen_w, screen_h):
        min_position = -1.2
        max_position = 0.6

        world_width = max_position - min_position
        scale = screen_w / world_width

        # x coordinate (this part was already right)
        x = (pos - min_position) * scale

        # ---- THIS is the important part ----
        y_scale = scale * 0.45
        y_offset = 0.55 * screen_h
        car_y_offset_px = 8  # magic constant used by Gym renderer

        y = screen_h - (np.sin(3 * pos) * y_scale + y_offset) - car_y_offset_px

        return int(x), int(y)

    def _overlay_trajectory_on_frame(self, frame, positions, upto_idx, cmap_name="plasma", radius=3, width=3):
        h, w = frame.shape[:2]
        img = Image.fromarray(frame)
        draw = ImageDraw.Draw(img)

        cmap = cm.get_cmap(cmap_name)
        n = max(1, len(positions) - 1)

        # draw segments up to current time
        for i in range(min(upto_idx, len(positions) - 1)):
            x1, y1 = self._mc_world_to_screen(positions[i], w, h)
            x2, y2 = self._mc_world_to_screen(positions[i + 1], w, h)

            r, g, b, _ = cmap(i / n)
            color = (int(255 * r), int(255 * g), int(255 * b))

            draw.line([(x1, y1), (x2, y2)], fill=color, width=width)
            draw.ellipse([(x2 - radius, y2 - radius), (x2 + radius, y2 + radius)], outline=color, width=2)

        return np.array(img)  

    def mountaincar_world_to_screen(pos, screen_w, screen_h):
        min_position = -1.2
        max_position = 0.6

        world_w = max_position - min_position
        scale = screen_w / world_w

        # x pixel (this part you already got right)
        x = (pos - min_position) * scale

        # Gym MountainCar renderer constants
        y_scale = scale * 0.45
        y_offset = 0.55 * screen_h
        car_y_offset_px = 8   # <<< THIS is the missing magic number

        y = screen_h - (np.sin(3 * pos) * y_scale + y_offset) - car_y_offset_px

        return int(x), int(y) 
    
    
    def plot_stage_state_diagram(
        self,
        frames,
        positions,
        velocities,
        stage_idx=None,
        save_path="figures/mountain_car/mountaincar_stages.png",
        annotate_state=True,
    ):
        """Create a diagram linking *world snapshots* to their corresponding (position, velocity) states.

        Top row: rendered frames at selected stages (a), (b), (c), ...
        Bottom row: phase plot (position vs velocity) with the selected stage points highlighted.

        Parameters
        ----------
        frames : list[np.ndarray]
            RGB frames from env.render(), length T
        positions : list[float]
            MountainCar positions, length T
        velocities : list[float]
            MountainCar velocities, length T
        stage_idx : list[int] | None
            Indices into the trajectory to snapshot. If None, uses [start, mid, end].
        save_path : str
            Output path for the PNG.
        annotate_state : bool
            If True, writes x/v on each snapshot panel.
        """
        import matplotlib.pyplot as plt
        from matplotlib.gridspec import GridSpec
        import numpy as np

        T = len(positions)
        if stage_idx is None:
            stage_idx = [0, T // 2, T - 1] if T >= 3 else list(range(T))
        stage_idx = [int(i) for i in stage_idx if 0 <= int(i) < T]
        if len(stage_idx) == 0:
            stage_idx = [0]

        pos = np.asarray(positions, dtype=float)
        vel = np.asarray(velocities, dtype=float)

        n = len(stage_idx)
        # fig = plt.figure(figsize=(4 * n, 6))
        # gs = GridSpec(2, n, height_ratios=[1.0, 1.2], hspace=0.15, wspace=0.05)
        fig = plt.figure(figsize=(4*n, 7.5))     # was too short
        gs = GridSpec(2, n, height_ratios=[1, 1.8], hspace=0.25, wspace=0.05)
        ax_phase = fig.add_subplot(gs[1, :])
        ax_phase.set_xlim(-1.2, 0.6)
        ax_phase.set_ylim(-0.07, 0.07)

        # Make the axes box have the same ratio as the data ranges
        xrange = 0.6 - (-1.2)      # 1.8
        yrange = 0.07 - (-0.07)    # 0.14
        ax_phase.set_box_aspect(yrange / xrange)  # ~0.078

        # ---- Phase plot (bottom, spanning all columns) ----
        ax_phase = fig.add_subplot(gs[1, 1])
        t = np.arange(T)
        ax_phase.scatter(pos, vel, c=t, s=18, cmap="plasma")
        ax_phase.plot(pos, vel, linewidth=1, color="gray", alpha=0.4)

        ax_phase.set_xlabel("Position")
        ax_phase.set_ylabel("Velocity")
        ax_phase.set_title("Trajectory in state space (highlighted stages)")
        

        # highlight chosen stages
        for j, idx in enumerate(stage_idx):
            ax_phase.scatter(pos[idx], vel[idx], s=160, facecolors="none", linewidths=3, edgecolors="black")
            ax_phase.text(pos[idx], vel[idx], f"  ({chr(97 + j)})", fontsize=14, va="center")

        # start/end markers
        ax_phase.scatter(pos[0], vel[0], s=70, marker="o", edgecolors="black")
        ax_phase.scatter(pos[-1], vel[-1], s=70, marker="o", edgecolors="black")

        ax_phase.set_aspect("equal", adjustable="box")

        ax_phase.grid(True, alpha=0.3)

        # ---- Snapshot frames (top row) ----
        for j, idx in enumerate(stage_idx):
            ax_img = fig.add_subplot(gs[0, j])
            ax_img.imshow(frames[idx])
            ax_img.axis("off")
            ax_img.set_title(f"({chr(97 + j)}) t={idx}/{T - 1}", fontsize=14)

            if annotate_state:
                ax_img.text(
                    0.02,
                    0.95,
                    f"x={pos[idx]:.3f}\nv={vel[idx]:.3f}",
                    transform=ax_img.transAxes,
                    fontsize=12,
                    va="top",
                    bbox=dict(boxstyle="round", alpha=0.6),
                )

        os.makedirs(os.path.dirname(save_path), exist_ok=True)
        plt.tight_layout()
        plt.savefig(save_path, dpi=200)
        plt.close(fig)
        return save_path

    def run_test_episode(self, num_episodes=1):
        for ep in range(num_episodes):
            if self.flat_vs_hierarchical == 'hierarchical':
                frames, positions, velocities, actions, V, time = self.run_episode_hierarchical(time_episode=True)
            else:
                frames, positions, velocities, actions, V, time = self.run_episode_flat(time_episode=True)
            filename_prefix="mountaincar_test"
            # ---- Save environment video ----
            mp4_filename = f"{filename_prefix}_{ep+1}.mp4"
            imageio.mimsave("figures/mountain_car/"+mp4_filename, frames, fps=30, macro_block_size=1)
            print(f"Saved video: {mp4_filename}")
            #Number of actions taken
            print(f"Number of actions taken: {len(actions)}")
            print(f"Actions taken: {actions}")
            #Number of macro states visited, macro actions
            macro_states_visited = [self.micro_to_macro[self.get_state_index(self.discretize_state([positions[i], velocities[i]]))] for i in range(len(positions))]
            unique_macro_states = set(macro_states_visited)
            print(f"Macro states visited: {macro_states_visited}")
            print(f"Unique macro states visited: {unique_macro_states}")
            macro_actions_taken = []
            for i in range(1, len(macro_states_visited)):
                if macro_states_visited[i] != macro_states_visited[i-1]:
                    macro_actions_taken.append((macro_states_visited[i-1], macro_states_visited[i]))
            print(f"Macro actions taken: {macro_actions_taken}")

            #Bar plot comparing number of actions vs macro actions
            plt.figure(figsize=(6,4))
            plt.bar(['Flat', 'Hierarchical'], [len(actions), len(macro_actions_taken)], color=['blue', 'orange'])
            #Add number labels on top of bars
            for i, v in enumerate([len(actions), len(macro_actions_taken)]):
                plt.text(i, v + 0.5, str(v), ha='center', fontsize=8)
            plt.xlabel('Policy Type')
            plt.ylabel('Number of Actions')
            plt.title('Number of actions: Flat vs Hierarchical')
            png_filename = f"{filename_prefix}_{ep+1}_action_comparison.png"
            plt.savefig("figures/mountain_car/" + png_filename)
            plt.close()
            print(f"Saved action comparison plot: {png_filename}")


            # ---- Save environment video WITH trajectory overlay ----
            os.makedirs("figures/mountain_car", exist_ok=True)

            overlay_frames = [
                self._overlay_trajectory_on_frame(frames[t], positions, upto_idx=t, cmap_name="plasma")
                for t in range(len(frames))
            ]

            mp4_filename = f"{filename_prefix}_overlay.mp4"
            imageio.mimsave("figures/mountain_car/" + mp4_filename, overlay_frames, fps=30, macro_block_size=1)
            print(f"Saved video: {mp4_filename}")

            png_filename = f"{filename_prefix}_{ep+1}_trajectory.png"
            final_overlay = self._overlay_trajectory_on_frame(frames[-1], positions, upto_idx=len(positions)-1, cmap_name="plasma")
            Image.fromarray(final_overlay).save("figures/mountain_car/" + png_filename)
            print(f"Saved trajectory overlay image: {png_filename}")

            # Color points by time (from first to last)
            cmap = plt.get_cmap("plasma")
            num_points = len(positions)

            # ---- Save trajectory plot ----
            plt.figure(figsize=(6, 5))
            colors = [cmap(i / (num_points - 1)) for i in range(num_points)]
            for i in range(num_points):
                plt.plot(positions[i], velocities[i], marker="o", markersize=4, color=colors[i])
            plt.plot(positions, velocities, linewidth=1, color="gray", alpha=0.5)
            print("initial pos, vel:", positions[0], velocities[0])
            print("final pos, vel:", positions[-1], velocities[-1])
            # Add legend for color mapping (first and last point)
            plt.scatter(positions[0], velocities[0], color=colors[0], label="Start", marker="o", s=40, edgecolor='black')
            plt.scatter(positions[-1], velocities[-1], color=colors[-1], label="End", marker="o", s=40, edgecolor='black')
            plt.legend(loc="best")
            plt.xlabel("Position")
            plt.ylabel("Velocity")
            plt.xticks(ticks=self.pos_space_regular, labels=np.round(self.pos_space, 3), fontsize=8)
            plt.yticks(ticks=self.vel_space_regular, labels=np.round(self.vel_space, 3), fontsize=8)
            plt.title(f"Trajectory Time: {time:.2f}s")
            plt.legend(loc="best")
            plt.grid(True)
            plt.tight_layout()
            png_filename = f"{filename_prefix}_{ep+1}_trajectory.png"
            plt.savefig("figures/mountain_car/"+png_filename)
            plt.close()
            print(f"Saved trajectory plot: {png_filename}")
            # ---- Save snapshot+state diagram (frames linked to phase plot) ----
            try:
                pos_arr = np.asarray(positions, dtype=float)
                # (a) start, (b) valley bottom (min position), (c) end
                idx_a = 0
                idx_b = int(np.argmin(pos_arr)) if len(pos_arr) > 0 else 0
                # idx_c = len(pos_arr) - 1
                goal_hits = np.where(pos_arr >= self.goal_position)[0]
                idx_c = int(goal_hits[0]) if len(goal_hits) > 0 else len(pos_arr) - 1
                stage_idx = [idx_a, idx_b, idx_c]
                stage_png = f"{filename_prefix}_{ep+1}_stages.png"
                self.plot_stage_state_diagram(
                    frames,
                    positions,
                    velocities,
                    stage_idx=stage_idx,
                    save_path="figures/mountain_car/" + stage_png,
                )
                print(f"Saved stage/state diagram: {stage_png}")
            except Exception as e:
                print(f"[WARN] Could not create stage/state diagram: {e}")


            # Trajectory plot with macro states colored 
            #TODO Fix for cases where it goes to default macro state
            if self.flat_vs_hierarchical == 'hierarchical':
                plt.figure(figsize=(6, 5))
                colors = [cmap(i / (self.n_clust- 1)) for i in range(self.n_clust)]
                for i in range(num_points):
                    macro_state = self.micro_to_macro[self.get_state_index(self.discretize_state([positions[i], velocities[i]]))]
                    plt.plot(positions[i], velocities[i], marker="o", markersize=4, color=colors[macro_state])
                plt.plot(positions, velocities, linewidth=1, color="gray", alpha=0.5)
                # Add legend for macro states
                for i in range(self.n_clust):
                    plt.scatter([], [], color=colors[i], label=f'{i}', marker="o", s=40, edgecolor='black')
                plt.scatter(positions[0], velocities[0], color=colors[0], label="Start", marker="o", s=40, edgecolor='black')
                plt.scatter(positions[-1], velocities[-1], color=colors[-1], label="End", marker="o", s=40, edgecolor='black')
                plt.xlabel("Position")
                plt.ylabel("Velocity")
                plt.xticks(ticks=self.pos_space_regular, labels=np.round(self.pos_space, 3), fontsize=8)
                plt.yticks(ticks=self.vel_space_regular, labels=np.round(self.vel_space, 3), fontsize=8)
                plt.title(f"Trajectory with Macro States")
                plt.legend(loc="best")
                plt.grid(True)
                plt.tight_layout()
                png_filename = f"{filename_prefix}_{ep+1}_trajectory_macro.png"
                plt.savefig("figures/mountain_car/"+png_filename)
                plt.close()
                print(f"Saved trajectory with macro states plot: {png_filename}")


            # ---- Plot actions ----
            plt.figure(figsize=(8, 6))
            scatter = plt.scatter(positions, velocities, c=actions, cmap='viridis', s=10)
            #Line connecting the points in order
            plt.plot(positions, velocities, color='gray', linewidth=0.5, alpha=0.5)
            plt.legend(*scatter.legend_elements(), title="Actions")
            plt.xlabel("Position")
            plt.ylabel("Velocity")
            plt.xticks(ticks=self.pos_space_regular, labels=np.round(self.pos_space, 3), fontsize=8)
            plt.yticks(ticks=self.vel_space_regular, labels=np.round(self.vel_space, 3), fontsize=8)
            plt.title(f"Actions Taken (Episode {ep+1})")
            plt.grid(True)
            plt.tight_layout()
            action_png_filename = f"{filename_prefix}_{ep+1}_actions.png"
            plt.savefig("figures/mountain_car/"+action_png_filename)
            plt.close()
            print(f"Saved actions plot: {action_png_filename}")

            vel_centers = 0.5 * (self.vel_space_regular[:-1] + self.vel_space_regular[1:])
            pos_centers = 0.5 * (self.pos_space_regular[:-1] + self.pos_space_regular[1:])

            #Plot V for debugging
            V_grid = V.reshape(self.n_pos_bins, self.n_vel_bins)
            
            plt.figure()
            plt.imshow(
                V_grid.T,
                aspect='auto',
                cmap='copper',
                extent=[self.pos_space[0], self.pos_space[-1], self.vel_space[0], self.vel_space[-1]],  # limits
            )
            plt.yticks(
                ticks = self.vel_space_regular,
                labels=np.round(self.vel_space, 3),
                fontsize=8
            )
            plt.xticks(
                ticks = self.pos_space_regular, # Since pos_space has 0.5 extra element
                labels=np.round(self.pos_space, 3),
                fontsize=8
            )

            #Add best action arrows
            arrows = {0:(-0.1,0), 2:(0.1,0)}
            scale = 0.1
            for r in range(self.n_pos_bins):
                for c in range(self.n_vel_bins):
                    s_idx = r * self.n_vel_bins + c
                    V_adj = []
                    for act in range(self.n_actions):
                        s_adj = self.B[:,:,act] @ idx_to_onehot(s_idx, self.N)
                        V_adj.append(V[onehot_to_idx(s_adj)])   
                    best_action = np.argmax(V_adj)
                    if best_action == 0:
                        plt.arrow(pos_centers[r] - scale * arrows[best_action][0],
                                vel_centers[c] - scale * arrows[best_action][1], scale * arrows[best_action][0],
                                    scale * arrows[best_action][1], head_width=0.01, head_length=0.05, color='g')  
                    elif best_action == 2:
                        plt.arrow(pos_centers[r] - scale * arrows[best_action][0],
                                vel_centers[c] - scale * arrows[best_action][1], scale * arrows[best_action][0],
                                    scale * arrows[best_action][1], head_width=0.01, head_length=0.05, color='r')
                    else:
                        plt.scatter(pos_centers[r], vel_centers[c], color='w')
                    s_adj = self.B[:,:,best_action] @ idx_to_onehot(s_idx, self.N)
                    s_adj_idx = onehot_to_loc(s_adj, self.n_vel_bins)
                    # plt.annotate(f'{s_adj_idx}', (pos_centers[r], vel_centers[c]), color='w', fontsize=6)   

            plt.xlabel("Position", fontsize=10)
            plt.ylabel("Velocity", fontsize=10)
            # plt.title(f"Value function V", fontsize=12)
            plt.colorbar(label="Value")
            plt.savefig(f"figures/matrices/V_mcar_{ep}.png", format="png")

            '''
            #Animate and save video
            line, = plt.plot([], [], lw=2)
            point, = plt.plot([], [], 'ro')

            def init():
                line.set_data([], [])
                point.set_data([], [])
                return line, point
            
            def animate(i):
                line.set_data([positions[:i]], [velocities[:i]])
                point.set_data([positions[i-1]], [velocities[i-1]])
                return line, point
            
            ani = animation.FuncAnimation(plt.gcf(), animate, frames=len(positions), init_func=init,    
                                        interval=100, blit=True)
            print("Saving trajectory animation...")
            ani.save(f'figures/mountain_car/mountain_car_trajectory_value{ep+1}.mp4')
            '''
            plt.close()
            
            plt.figure()
            # plt.imshow(
            #     V_grid.T,
            #     aspect='auto',
            #     cmap='copper',
            #     extent=[self.pos_space[0], self.pos_space[-1], self.vel_space[0], self.vel_space[-1]],  # limits
            # )
            plt.yticks(
                ticks = self.vel_space_regular,
                labels=np.round(self.vel_space, 3),
                fontsize=8
            )
            plt.xticks(
                ticks = self.pos_space_regular, # Since pos_space has 0.5 extra element
                labels=np.round(self.pos_space, 3),
                fontsize=8
            )
            
            plt.xlim(self.pos_space[0], self.pos_space[-1])
            plt.ylim(self.vel_space[0], self.vel_space[-1])
            
            plt.xlabel("Position", fontsize=10)
            plt.ylabel("Velocity", fontsize=10)
            plt.title(f"Trajectory", fontsize=12)
            
            line, = plt.plot([], [], lw=2)
            point, = plt.plot([], [], 'ro')

            def init():
                line.set_data([], [])
                point.set_data([], [])
                return line, point
            
            def animate(i):
                line.set_data([positions[:i]], [velocities[:i]])
                point.set_data([positions[i-1]], [velocities[i-1]])
                return line, point
            
            ani = animation.FuncAnimation(plt.gcf(), animate, frames=len(positions), init_func=init,    
                                        interval=100, blit=True)
            print("Saving trajectory animation...")
            ani.save(f'figures/mountain_car/mountain_car_trajectory_{ep+1}.mp4')
            plt.close()
            
            if self.flat_vs_hierarchical == 'hierarchical':
                #Same trajectory animation but with macro actions/states colored
                plt.figure()
                plt.yticks(
                ticks = self.vel_space_regular,
                labels=np.round(self.vel_space, 3),
                fontsize=8
                )
                plt.xticks(
                    ticks = self.pos_space_regular, # Since pos_space has 0.5 extra element
                    labels=np.round(self.pos_space, 3),
                    fontsize=8
                )
                
                positions = np.asarray(positions)
                velocities = np.asarray(velocities)
                
                macro_states = []
                for i in range(len(positions)):
                    s_idx = self.get_state_index(self.discretize_state([positions[i], velocities[i]]))
                    macro_states.append(self.micro_to_macro[s_idx])
                macro_states = np.array(macro_states)
                points = np.column_stack([positions, velocities])
                segments = np.stack([points[:-1], points[1:]], axis=1)
                
                seg_macro_states = macro_states[:-1]
                
                #Ignoring background cluster 0 for coloring
                raw_colors = [cmap(m / (self.n_clust - 1)) for m in seg_macro_states]
                colors = []
                for i, (m,c) in enumerate(zip(seg_macro_states, raw_colors)):
                    if m == 0 and i > 0:
                        colors.append(colors[-1])  # Repeat previous color
                    else:
                        colors.append(c)
                fig, ax = plt.subplots()
                ax.set_xlabel("Position", fontsize=10)
                ax.set_ylabel("Velocity", fontsize=10)
                ax.set_title("Trajectory with macro actions", fontsize=12)
                #Add legends
                # patches = [ mpatches.Patch(color=cmap(i / (self.n_clust - 1)), label=f'{i}' ) for i in range(1,self.n_clust-1) ]
                # plt.legend(handles=patches, loc='best')
                
                
                lc = LineCollection([], linewidths=2)   # start empty
                
                ax.add_collection(lc)

                # point marker
                (point,) = ax.plot([], [], 'ro')

                # set reasonable axis limits
                ax.set_xlim(self.pos_space[0], self.pos_space[-1])
                ax.set_ylim(self.vel_space[0], self.vel_space[-1])

                def init():
                    lc.set_segments([])          # no segments at start
                    point.set_data([], [])
                    return lc, point

                def animate(i):
                    """
                    i goes from 1 to len(positions)-1 (since segments are between i-1 and i).
                    At frame i, we show segments[:i], each already having its own color.
                    """
                    if i == 0:
                        return lc, point

                    # show segments up to frame i
                    lc.set_segments(segments[:i])
                    # assign colors for these segments
                    lc.set_color(colors[:i])

                    # update moving point
                    point.set_data([positions[i]], [velocities[i]])
                    return lc, point

                ani = animation.FuncAnimation(
                    fig,
                    animate,
                    frames=len(positions)-1,
                    init_func=init,
                    interval=100,
                    blit=True,
                )
                
                writer = animation.FFMpegWriter(
                    fps=30,
                    codec="libx264",
                    bitrate=2500,
                    extra_args=["-pix_fmt", "yuv420p", "-an"]
                )
                print("Saving trajectory with macro states animation...")
                ani.save(
                    f'figures/mountain_car/mountain_car_trajectory_macro_{ep+1}.mp4',
                    writer=writer  
                )

                # plt.show()



                # def init():
                #     line.set_data([], [])
                #     point.set_data([], [])
                #     return line, point
                # def animate(i):
                #     macro_state = self.micro_to_macro[self.get_state_index(self.discretize_state([positions[i-1], velocities[i-1]]))]
                #     macro_color = colors[macro_state]
                #     line.set_data([positions[:i]], [velocities[:i]])
                #     point.set_data([positions[i-1]], [velocities[i-1]])
                #     line.set_color(macro_color)
                #     return line, point
                # ani = animation.FuncAnimation(plt.gcf(), animate, frames=len(positions), init_func=init,
                #                             interval=100, blit=True)
                
                # ani.save(f'figures/mountain_car/mountain_car_trajectory_macro_{ep+1}.mp4')
                plt.close()
            
            
def SR_performance_Hierarchy(args):

    inverse_factor = 4
    render_mode = 'rgb_array'  # set to "human" to watch training
    env = gym.make("MountainCar-v0", render_mode=render_mode)#, max_episode_steps=1000)
    agent = SR_Agent_Hierarchy(env, gamma=args.gamma, alpha=args.alpha, n_pos_bins=n_pos_bins, n_vel_bins=n_vel_bins, inverse_factor=inverse_factor,
    n_clust = args.n_macro, init_state=args.init_state, goal_loc=args.goal_loc, learn_likelihood=args.learn_likelihood, flat_vs_hierarchical=args.flat_vs_hierarchical)

    train_episodes = args.train_episodes
    test_episodes = args.test_episodes
    agent.learn_env_likelihood(train_episodes)
    env= gym.make("MountainCar-v0", render_mode=render_mode, max_episode_steps=args.test_steps)
    agent.env = env
    agent.run_test_episode(num_episodes=test_episodes)

    
if __name__ == '__main__':
    # TODO: Generalize to other n pos bins
    n_pos_bins    = 8
    n_vel_bins    = 8
    gamma         = 0.99
    alpha         = 0.01
    epsilon_start = 1.0
    epsilon_end   = 0.01
    epsilon_decay = 0.995 
    train_episodes      = 6000
    test_episodes = 1
    eval_interval = 500
    init_state = [-0.5, 0]
    goal_loc = None
    learn_likelihood = False
    n_macro = 8
    manually_set_macro_states = False
    #TODO: FIX MACRO CLUSTERING TO BE MORE SENSIBLE
    test_steps = 500
    render_mode = None  # set to "human" to watch training
    flat_vs_hierarchical = 'hierarchical'  # set to "flat" to run flat policy
        
    parser = argparse.ArgumentParser(description="Arguments for hierarchical model")
    parser.add_argument("n_pos_bins", nargs='?',type=int, default=n_pos_bins, help="Number of position bins")
    parser.add_argument("n_vel_bins", nargs='?',type=int, default=n_vel_bins, help="Number of velocity bins")
    parser.add_argument("gamma", nargs='?',type=float, default=gamma, help="Discount factor")
    parser.add_argument("alpha", nargs='?',type=float, default=alpha, help="Learning rate")
    parser.add_argument("epsilon_start", nargs='?',type=float, default=epsilon_start, help="Initial epsilon")
    parser.add_argument("epsilon_end", nargs='?',type=float, default=epsilon_end, help="Final epsilon")
    parser.add_argument("epsilon_decay", nargs='?',type=float, default=epsilon_decay, help="Epsilon decay rate")
    parser.add_argument("init_state", nargs='?',type=list, default=init_state, help="Initial state")
    parser.add_argument("goal_loc", nargs='?',type=float, default=goal_loc, help="Goal location")
    parser.add_argument("learn_likelihood", nargs='?',type=bool, default=learn_likelihood, help="Whether to learn environment likelihood")
    parser.add_argument("train_episodes", nargs='?',type=int, default=train_episodes, help="Number of training episodes")
    parser.add_argument("eval_interval", nargs='?',type=int, default=eval_interval, help="Evaluation interval")
    parser.add_argument("n_macro", nargs='?',type=int, default=n_macro, help="Number of macro states")
    parser.add_argument("test_episodes", nargs='?',type=int, default=test_episodes, help="Number of test episodes")
    parser.add_argument("flat_vs_hierarchical", nargs='?',type=str, default=flat_vs_hierarchical, help="Choose between flat and hierarchical policy")
    parser.add_argument("test_steps", nargs='?',type=int, default=test_steps, help="Number of test steps")
    parser.add_argument("render_mode", nargs='?',type=str, default=render_mode, help="Render mode")
    parser.add_argument("manually_set_macro_states", nargs='?',type=bool, default=manually_set_macro_states, help="Manually set macro states")
    args = parser.parse_args()
    
    print('Hierarchical Model')
    print('*'*50)
    SR_performance_Hierarchy(args)
    print('*'*50)
    
    
    # if not os.path.exists("data/"):
    #     os.makedirs("data/")

    # np.save("data/SR_steps.npy", N_steps)
    # np.save("data/SR_rewards.npy", total_r)
    # np.save("data/SR_times.npy", total_time)
