'''
Hierarchical model of gridworld.
Here the macro states are generated by clustering the successor matrix. 
No neural networks are used for the macro actions.
A smoother version of hierarchy with respect to episodes is implemented.
When having trials for different number of episodes, it continues the same run 
and doesn't start from zero.
This version also orders the clusters so that we get the same successor matrix
at the higher level for each run.
'''
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)

import numpy as np
from utils import *
from env import *
import matplotlib.pyplot as plt
from matplotlib.cm import get_cmap
from sklearn.cluster import SpectralClustering
from sklearn.manifold import SpectralEmbedding

import matplotlib.animation as animation
import matplotlib.patches as mpatches
from copy import deepcopy
import time
import random
from matplotlib.colors import LogNorm
from collections import Counter, defaultdict
import os
import glob

import torch
from torch import nn
import torch.nn.functional as F
from torch.distributions import Categorical
from nn import *

import argparse
import sys
np.set_printoptions(threshold=sys.maxsize)



class SR_Agent_Hierarchy(object):
    def __init__(self, env, A=None,B=None,C=None, discount_factor=0.99,inverse_factor=1, n_clust = 4, 
                 init_loc = None, goal_loc = None, goal_val = 100, num_episodes=None, learn_likelikood = False):
        if A is None:
            self.A = env.get_likelihood_dist()
        else:
            self.A = A
        self.env = env
        self.B = B
        self.B_macro = None
        self.M = None
        
        if init_loc is None:          
            self.init_loc = (0, 0)
        else:
            self.init_loc = init_loc
            
        if goal_loc is None:
            goal_loc = (env.grid_size,env.grid_size)
            self.goal_idx = env.grid_size**2 - 1
        else:
            self.goal_idx = loc_to_idx(goal_loc,env.grid_size)
            
        if C is not None:
            self.C = C
        else:
            self.C = np.ones(env.grid_size**2) * -0.1
            self.C[self.goal_idx] = goal_val
        self.C_macro = None
        self.gamma = discount_factor
        self.inverse_factor = inverse_factor
        
        self.env.get_image(self.init_loc, goal_loc)
        self.s = None
        self.s_array = None
        self.a_array = None
        self.max_s = idx_to_onehot(np.argmax(self.C), self.env.grid_size)
        self.learn_likelikood = learn_likelikood
        self.n_clust = n_clust
        self.n_actions = 4
        self.n_macro_actions = None
        if num_episodes is None:
            self.num_episodes = 0 # Keep track of number of episodes
        else:
            self.num_episodes = num_episodes
        self.learning_rate = 0.05 
        # self.learn_env_likelikood()

    def view_matrices(self):
        if self.learn_likelikood:
            learn_str = 'estimated'
        else:
            learn_str = 'actual'
        B_avg = np.sum(self.B, axis=2) / self.B.shape[-1]
        plt.figure()
        plt.title("Default Policy B Matrix",fontsize=20)
        plt.imshow(B_avg)#, norm=LogNorm(vmin=B_avg.min(), vmax=B_avg.max()))
        plt.xticks(list(range(0,self.env.grid_size**2)),fontsize=12)
        plt.yticks(list(range(0, self.env.grid_size**2)),fontsize=12)
        plt.savefig(f"figures/matrices/B_matrix_micro.png", format="png")
        plt.close()

        plt.figure()
        plt.imshow(self.M, aspect='equal', cmap='cividis')#, norm=LogNorm(vmin=self.M.min(), vmax=self.M.max()))
        plt.xticks(list(range(0,self.env.grid_size**2)),fontsize=12)
        plt.yticks(list(range(0,self.env.grid_size**2)),fontsize=12)
        plt.title(f"Successor Matrix M ({learn_str})", fontsize=20)
        plt.savefig(f"figures/matrices/m_{learn_str}_micro.png", format="png")
        plt.close()
        np.save("data/M.npy", self.M)

        M_orig = self.M[0,:].reshape(self.env.grid_size,self.env.grid_size).T
        plt.figure()
        plt.imshow(M_orig, aspect='equal', cmap='copper', norm=LogNorm(vmax=M_orig.max()))
        plt.xticks(list(range(0,self.env.grid_size)),fontsize=12)
        plt.yticks(list(range(0,self.env.grid_size)),fontsize=12)
        # plt.title(f"Successor Matrix M from start({learn_str})", fontsize=20)
        plt.savefig(f"figures/matrices/m_origin_{learn_str}.png", format="png")
        plt.close()
        
        B_macro_avg = np.sum(self.B_macro, axis=2) / self.n_macro_actions
        plt.figure()
        plt.title("Default Policy B Matrix",fontsize=20)
        plt.imshow(B_macro_avg)#, norm=LogNorm(vmin=B_avg.min(), vmax=B_avg.max()))
        plt.xticks(list(range(0,self.n_clust)),fontsize=12)
        plt.yticks(list(range(0, self.n_clust)),fontsize=12)
        for i in range(len(B_macro_avg)):
            for j in range(len(B_macro_avg)):
                plt.text(j, i, f'{B_macro_avg[i, j]:.2f}',
                            ha="center", va="center", color="w")
        plt.savefig(f"figures/matrices/B_matrix_macro.png", format="png")
        plt.close()

        plt.figure()
        plt.imshow(self.M_macro, aspect='equal', cmap='cividis')#, norm=LogNorm(vmin=self.M.min(), vmax=self.M.max()))
        plt.xticks(list(range(0,self.n_clust)),fontsize=12)
        plt.yticks(list(range(0,self.n_clust)),fontsize=12)
        plt.title(f"Successor Matrix M ({learn_str})", fontsize=20)
        for i in range(len(self.M_macro)):
            for j in range(len(self.M_macro)):
                plt.text(j, i, f'{self.M_macro[i, j]:.2f}',
                            ha="center", va="center", color="w")
        plt.savefig(f"figures/matrices/m_{learn_str}_macro.png", format="png")
        plt.close()

    def show_actions(self):

        gs = self.env.grid_size
        fig = plt.figure()
        grid = np.zeros((gs, gs))
        if len(self.env.walls) > 0:
            wall_idx = tuple(np.array(self.env.walls).T)
        start_loc = self.init_loc
        
        if isinstance(self.goal_idx, int):
            goal_loc = [idx_to_loc(self.goal_idx, gs)]
        else:   
            goal_loc = [idx_to_loc(gidx, gs) for gidx in self.goal_idx]
        grid[start_loc] = 1
        grid[wall_idx] = 2
        grid[tuple(zip(*goal_loc))] = 0.5

        arrows = {1:(1,0), 0:(-1,0),3:(0,1),2:(0,-1)}
        scale = 0.25
        arrows_grid = np.full((gs, gs),-1)
        s_idxs = [onehot_to_loc(s, gs) for s in self.s_array]
        for i in range(1,len(self.a_array)):
            arrows_grid[s_idxs[i]] = self.a_array[i]
        arrows_grid = arrows_grid.T
        
        fig, ax = plt.subplots(figsize=(gs,gs))
        for r, row in enumerate(arrows_grid):
            for c, cell in enumerate(row):
                if cell in arrows:
                    plt.arrow(c-scale*arrows[cell][0], r-scale*arrows[cell][1], scale*arrows[cell][0], scale*arrows[cell][1], head_width=0.15,color='w')

        cmap = colors.ListedColormap(['black','purple','yellow','white'])

        im = plt.imshow(grid.T, aspect='equal', cmap=cmap)
        # plt.title(f'Gridworld of size {gs}')
        ax = plt.gca()

        for goal in goal_loc:
                ax.text(goal[0], goal[1], 'Goal', fontsize = 18, ha="center", va="center", color="w")
        ax.text(start_loc[0], start_loc[1], 'Agent', fontsize = 18, ha="center", va="center", color="b")
        # for widx in self.env.walls:
        #     ax.text(widx[0], widx[1], 'Wall', fontsize = 10, ha="center", va="center", color="w")

        # Major ticks
        ax.set_xticks(np.arange(0, gs, 1))
        ax.set_yticks(np.arange(0, gs, 1))

        # Labels for major ticks
        ax.set_xticklabels(range(0, gs))
        ax.set_xticklabels(range(0, gs))

        # Minor ticks
        ax.set_xticks(np.arange(-.5, gs, 1), minor=True)
        ax.set_yticks(np.arange(-.5, gs, 1), minor=True)

        # Gridlines based on minor ticks
        ax.grid(which='minor', color='w', linestyle='-', linewidth=2)

        # Remove minor ticks
        ax.tick_params(which='minor', bottom=False, left=False)

        # plt.title(f"Actions taken", fontsize=20)
        plt.savefig(f"figures/Actions_taken.png", format="png")
        plt.close()
    
    def visualize_policy(self):
        
        # Clear out old images
        for filename in glob.glob("figures/Macro Action Network/Macro_Action_Network_*"):
            os.remove(filename) 

        
        grid_size = self.env.grid_size

        for macro_state in range(self.n_clust):
            for macro_action, macro_final_state in enumerate(self.adj_list[macro_state]):
                final_state = self.bottleneck_states[(macro_state, macro_final_state)][0]
                C = idx_to_onehot(final_state, grid_size)
                V = self.M @ C
                print(f'\nInitial state: Micro - {macro_state}')
                print(f'Final state: Micro - {final_state}, Macro - {macro_final_state}')
                arrows_grid = np.full((grid_size,grid_size),-1)
                for state in self.macro_state_list[macro_state]:
                    V_adj = []
                    for act in range(self.n_actions):
                        s_adj = self.B[:,:,act] @ idx_to_onehot(state, grid_size)
                        V_adj.append(V[onehot_to_idx(s_adj)])   
                    # ba_gen = (ele for ele in np.argsort(V_adj)[::-1])
                    best_action = np.argmax(V_adj)
                    arrows_grid[idx_to_loc(state,grid_size)] = best_action
                    
                arrows_grid = arrows_grid.T
                
                plt.figure()
                arrows = {1:(1,0), 0:(-1,0),3:(0,1),2:(0,-1)}
                scale = 0.25
        
                plt.xticks(np.arange(grid_size),fontsize=12)
                plt.yticks(np.arange(grid_size),fontsize=12)
                fig, ax = plt.subplots(figsize=(grid_size,grid_size))
                for r, row in enumerate(arrows_grid):
                    for c, cell in enumerate(row):
                        if cell in arrows:
                            plt.arrow(c-scale*arrows[cell][0], r-scale*arrows[cell][1], scale*arrows[cell][0], scale*arrows[cell][1], head_width=0.15,color='w')
                im = plt.imshow(self.lg,cmap='gist_heat')
                colours = im.cmap(im.norm(np.unique(self.lg)))
                
                #Just to add labels for the macro actions in the figure
                patches = [ mpatches.Patch(color=colours[i], label=f'{i}' ) for i in range(len(colours)-1) ]
                plt.legend(handles=patches, bbox_to_anchor=(1.05, 1), loc=2, borderaxespad=0.)
                plt.title(f"Macro Action Policy from state {macro_state} to {macro_final_state}", fontsize=20)
                plt.savefig(f"figures/Macro Action Network/Macro_Action_Network_{macro_state}_{macro_final_state}.png", format="png")
                plt.tight_layout()
                plt.close()


    def update_sr(self, current_exp, next_exp, M):
        # SARSA TD learning rule
        # Modifies M
        grid_size =  self.env.grid_size
        s_1 = current_exp[0]
        #a_1 = current_exp[1]
        s_2 = current_exp[2]
        #a_2 = next_exp[1]
        r = current_exp[3]
        done = current_exp[4]
        I = idx_to_onehot(s_2, grid_size)
        if done:            
            td_error = (I + self.gamma * idx_to_onehot(s_2, grid_size) - M[s_1,:])
        else:
            td_error = (I + self.gamma * M[s_2, :] - M[s_1,:])
        M[s_1,:] += self.learning_rate * td_error
        return td_error


    def actual_successor_transition_matrix(self):
        env = self.env
        grid_size = self.env.grid_size

        self.B = env.get_transition_dist()
        I = np.identity(grid_size**2)
        B_avg = np.sum(self.B, axis=2) / self.n_actions
        self.M = np.linalg.inv(I - (0.95 * B_avg))
        return self.B, self.M
    

    def show_video(self):
        #print(self.s_array)
        gs = self.env.grid_size

        fig = plt.figure()
        grid = np.zeros((gs, gs))
        if len(self.env.walls) > 0:
            wall_idx = tuple(np.array(self.env.walls).T) # Convert  to right format
        start_idx = self.init_loc
        goal_idx = idx_to_loc(self.goal_idx, gs)
        grid[start_idx] = 1
        grid[goal_idx] = 0.5
        grid[wall_idx] = 0.25
        im = plt.imshow(grid.T, aspect='equal', cmap='magma')
        plt.title(f'Gridworld of size {gs}')
        
        ax = plt.gca()
        
        # Major ticks
        ax.set_xticks(np.arange(0, gs, 1))
        ax.set_yticks(np.arange(0, gs, 1))

        # Labels for major ticks
        ax.set_xticklabels(np.arange(gs, 1))
        ax.set_yticklabels(np.arange(gs, 1))

        # Minor ticks
        ax.set_xticks(np.arange(-.5, gs, 1), minor=True)
        ax.set_yticks(np.arange(-.5, gs, 1), minor=True)

        # Gridlines based on minor ticks
        ax.grid(which='minor', color='w', linestyle='-', linewidth=2)

        # Remove minor ticks
        ax.tick_params(which='minor', bottom=False, left=False)

        past_idx_array = []

        def init():
            grid = np.zeros((gs, gs))
            grid[wall_idx] = 0.25
            grid[start_idx] = 1
            grid[goal_idx] = 0.5
            im.set_data(grid)
            return im,


        def animate(i):
            for txt in ax.texts[::-1]:
                txt.remove()
            s = self.s_array[i]
            grid = np.zeros((gs, gs))
            grid[wall_idx] = 0.25
            s_idx = onehot_to_loc(s, gs)
            grid[s_idx] = 1
            grid[goal_idx] = 0.5
            
            # for past_idx in past_idx_array:
            #     grid[past_idx] = 0.01
            grid[s_idx] = 1
            past_idx_array.append(s_idx)
            im.set_data(grid.T)

            
            ax.text(s_idx[0], s_idx[1], 'Agent', fontsize = 10, ha="center", va="center", color="b")
            ax.text(goal_idx[0], goal_idx[1], 'Goal', fontsize = 10, ha="center", va="center", color="w")
            for idx in self.env.walls:
                ax.text(idx[0], idx[1], 'Wall', fontsize = 10, ha="center", va="center", color="w")
                
            if i > 0:
                ax.scatter(past_idx_array[i-1][0], past_idx_array[i-1][1], color='y')
            if i == len(self.s_array) - 2:
                plt.savefig(f'figures/trajectory.png')
            # ax.scatter(s_idx[0], s_idx[1], color='y')

            return im,
        ani = animation.FuncAnimation(fig, animate, np.arange(len(self.s_array)), init_func=init,
                              interval=500, blit=True)
        ani.save(f'videos/env_micro.mp4')
        plt.close()
         
        
    def env_reset(self,init=None, verbose=False):
        self.s = self.env.reset(init)
        self.s_array = [self.s]
        self.a_array = []
        if verbose:
            print('Micro State')
            print("Init S: ", self.env.get_state_loc())
            #print("max_s: ", self.max_s)
            print('walls',self.env.walls)
        return self.s
    
    def learn_successor_transition_matrix(self, num_episodes):
        env = self.env
        grid_size = self.env.grid_size
        N = grid_size**2

        if self.M is None:
            self.B = np.zeros((N,N,self.n_actions))
            self.M = np.zeros((N,N))
        

        max_s = np.argmax(self.C)
        # num_episodes = self.num_episodes - self.num_episodes//4
        train_episode_length = 40
        experiences = []
        lifetime_td_errors = []

        for ep in range(num_episodes):
            s = onehot_to_idx(self.env_reset())
            episodic_error = []
            for j in range(train_episode_length):
                action = random.randrange(self.n_actions)
                s_next = onehot_to_idx(env.step(action))
                done = False #(s == max_s)      
                self.B[s_next, s, action] += 1   # Update B  
                experiences.append([s, action, s_next, self.C[s_next], done])
                # print(experiences)
                s = s_next
                if (j > 1):
                    td_sr = self.update_sr(experiences[-2], experiences[-1],self.M)
                    episodic_error.append(np.mean(np.abs(td_sr)))
                if done:
                    td_sr = self.update_sr(experiences[-1], experiences[-1],self.M)
                    episodic_error.append(np.mean(np.abs(td_sr)))
                    break
            lifetime_td_errors.append(np.mean(episodic_error))

        # Handling transitions not encountered by manually adding a P(s_t+1=a|s_t=a)=1
        for col in range(N):
            for action in range(self.n_actions):
                col_sum = np.sum(self.B[:,col,action])
                if col_sum == 0:
                    self.B[col,col,action] = 1
        # Normalize matrix
        self.B = self.B/self.B.sum(axis=0, keepdims=True)
        self.B[max_s, max_s, :] = 1
        print('Learning Complete')

        return self.B, self.M
    
    def learn_successor_transition_matrix_macro(self):
        N = self.n_clust
        action_list = self.adj_list
        A = self.n_macro_actions   
        B = np.zeros((N,N,A))
        M = np.zeros((N,N))

        for state in range(N):
            if state not in action_list:
                B[state,state,0] += 1
                continue
            for ind,val in enumerate(action_list[state]):
                B[val,state,ind] += 1
                
        I = np.eye(N)

        # Handling transitions not encountered by manually adding a P(s_t+1=a|s_t=a)=1
        for col in range(N):
            for action in range(A):
                col_sum = np.sum(B[:,col,action])
                if col_sum == 0:
                    B[col,col,action] = 1
        # Normalize matrix
        B = B/B.sum(axis=0, keepdims=True)
        B_avg = np.sum(B, axis=2)
        B_avg = B_avg/np.sum(B_avg, axis=1)[:,np.newaxis] 
        M = np.linalg.pinv(I - (0.9 * B_avg))
        return B, M
    
    
    def learn_macro_clusters(self):
        grid_size = self.env.grid_size
        N = self.env.grid_size**2
        mask = np.full(N,True)
        walls = [loc_to_idx(wall, grid_size) for wall in self.env.get_walls()]
        mask[walls] = False
        Mf = self.M[mask,:][:,mask]
        
        mask_ind = [i for i in range(len(mask)) if mask[i]]
        
        n_clust=self.n_clust
        Mf = np.maximum(Mf, Mf.transpose()) # To fix symmetry issues
 
        pos = SpectralEmbedding(n_components=2, affinity='precomputed').fit_transform(Mf)
        pos_walls = np.zeros((N,2))
        pos_walls[mask] = pos

        labels = np.ones(N) * n_clust  
        sc = SpectralClustering(n_clust, affinity='precomputed', n_init=100,
                        assign_labels='discretize')
  
        '''
        Swapping the order of the clusters to have a more regular order
        We keep the highest index corresponding to the walls as the same,
        and then sort the rest of the clusters in terms of their order 
        with respect to the micro state indices.
        '''
        labels[mask_ind] = sc.fit_predict(Mf)
        label_order, new_ind = np.unique(labels, return_index=True)
        label_order = label_order[np.argsort(new_ind)]
        label_order = np.delete(label_order, label_order == n_clust)
        label_order = np.append(label_order, n_clust)
        mapping = dict(zip(label_order, np.arange(n_clust+1)))
        labels = np.array([mapping[l] for l in labels])

        labels_grid = labels.reshape(grid_size,grid_size).T   
  
        self.lg = labels_grid
        
        # Last cluster is set of walls which isn't added to state list s in the end
        counts = Counter(labels)
        R = defaultdict(list)
        for i,n in enumerate(labels):
            R[n].append(i)
        s = [R[i] for i in range(n_clust)] 
        
        inv_s = {}
        for k, seq in enumerate(s):
            for idx in seq:
                inv_s[idx] = k
        print('Clustering complete')
        
        plt.figure()
        im = plt.imshow(labels_grid,cmap='gist_heat')
        colours = im.cmap(im.norm(np.unique(labels_grid))) # Colours including walls as separate colour (white)
        plt.xticks(np.arange(grid_size),fontsize=12)
        plt.yticks(np.arange(grid_size),fontsize=12)
        # plt.title(f"Macro state clusters", fontsize=20)
        patches = [ mpatches.Patch(color=colours[i], label=f'{i}' ) for i in range(len(colours)-1) ]
        plt.legend(handles=patches, bbox_to_anchor=(1.05, 1), loc=2, borderaxespad=0.)
        plt.savefig(f"figures/clustering/Macro_s.png", format="png")
        plt.close()
        
        plt.figure()
        for i, lst in enumerate(s):
            plt.scatter(pos_walls[lst,0], pos_walls[lst,1], label=f'{i}',color=colours[i], s=75)
        # for i, state in enumerate(np.arange(N)[mask]):
        #     plt.annotate(state, pos[i,:])
        plt.legend()
        # plt.title('Micro states clusters')
        plt.savefig('figures/clustering/macro_state_viz.png')
        plt.close()
        return s, inv_s
    
    def learn_adjacency(self, num_episodes):
        env = self.env
        grid_size = self.env.grid_size

        N = grid_size**2
        max_s = np.argmax(self.C)

        train_episode_length = 40
        experiences = []
        lifetime_td_errors = []

        adj_list = defaultdict(set)
        bottleneck_states = defaultdict(set)
        # Learn which macro states are adjacent, and also improver M further using the new info we have
        for ep in range(num_episodes):
            s = onehot_to_idx(env.reset())
            episodic_error = []
            for j in range(train_episode_length):
                action = random.randrange(self.n_actions)
                s_next = onehot_to_idx(env.step(action))
                done = False#(s == max_s)      
                # self.B[s_next, s, action] += 1   # Update B  
                experiences.append([s, action, s_next, self.C[s_next], done])
                s_macro = self.micro_to_macro[s]
                s_next_macro = self.micro_to_macro[s_next]
                if s_macro != s_next_macro:
                    adj_list[s_macro].add(s_next_macro)
                    bottleneck_states[(s_macro,s_next_macro)].add(s_next)
                    
                # print(experiences)
                s = s_next
                if (j > 1):
                    td_sr = self.update_sr(experiences[-2], experiences[-1],self.M)
                    episodic_error.append(np.mean(np.abs(td_sr)))
                if done:
                    td_sr = self.update_sr(experiences[-1], experiences[-1],self.M)
                    episodic_error.append(np.mean(np.abs(td_sr)))
                    break
            lifetime_td_errors.append(np.mean(episodic_error))
        bottleneck_states = {k:list(v) for k,v in bottleneck_states.items()}
        adj_list = {k:list(v) for k,v in adj_list.items()}
        self.n_macro_actions = max(len(v) for k,v in adj_list.items())            
        return adj_list, bottleneck_states
        
    def execute_macro_action(self, init_state, final_state):
        env = self.env
        grid_size = env.grid_size
        
        #for bottleneck_state in self.bottleneck_states[(init_state, final_state)]: break# Obtain element from set of size 1
        bottleneck_state = self.bottleneck_states[(init_state, final_state)][0]
        C = idx_to_onehot(bottleneck_state, grid_size)
        V = self.M @ C
        
        print('Current state',self.env.get_state_loc())
        N_steps = 0
        total_r = 0
        
        while (self.s != C).any() and (self.s != self.max_s).any():   
            s_left = self.B[:,:,0] @ self.s
            s_right = self.B[:,:,1] @ self.s
            s_up = self.B[:,:,2] @ self.s
            s_down = self.B[:,:,3] @ self.s
        
            V_left = V[onehot_to_idx(s_left)]
            V_right = V[onehot_to_idx(s_right)]
            V_up = V[onehot_to_idx(s_up)]
            V_down = V[onehot_to_idx(s_down)]

            ba_gen = (ele for ele in np.argsort([V_left, V_right, V_up, V_down])[::-1])
            best_action = next(ba_gen)
            # so now we actually take the next action
            s_new = env.step(best_action)
            while (self.s == s_new).all():
                best_action = next(ba_gen)
                s_new = env.step(best_action)
            # print(best_action,end=' ')

            self.s = s_new 
            self.s_array.append(self.s)
            self.a_array.append(best_action)
            r = self.C[onehot_to_idx(self.s)]
            total_r += r

            print('s:',self.env.get_state_loc())
            N_steps +=1
            if N_steps > 4*self.env.grid_size:
                break
        print('End state',self.env.get_state_loc())
        return N_steps, total_r
        

    def learn_env_likelikood(self, num_episodes=None):
        if num_episodes is None:
            num_episodes = 500
        self.num_episodes += num_episodes
        if self.learn_likelikood:
            self.B, self.M = self.learn_successor_transition_matrix(num_episodes - num_episodes//self.n_actions)
            # _, self.M = self.actual_successor_transition_matrix()
            
        else:
            self.B, self.M = self.actual_successor_transition_matrix()
        self.macro_state_list, self.micro_to_macro = self.learn_macro_clusters()
        # print(self.macro_state_list, self.micro_to_macro)
        
        # Create C macro now that we have macro states
        self.C_macro = np.zeros(self.n_clust)
        for i in range(self.n_clust):
            self.C_macro[i] = np.sum(self.C[self.macro_state_list[i]])
        print('C_macro',self.C_macro)
        # self.C_macro = np.ones(self.n_clust) * -0.1
        # self.C_macro[self.micro_to_macro[self.goal_idx]] = 50
        self.adj_list, self.bottleneck_states = self.learn_adjacency(num_episodes//self.n_actions)
        print('adj', self.adj_list)
        print('bs',self.bottleneck_states)
        self.B_macro, self.M_macro =  self.learn_successor_transition_matrix_macro()

    
    def run_episode(self, time_episode = True):       
        if time_episode == True:
            start_time = time.time()
        grid_size = self.env.grid_size
        
        # self.view_matrices()

        previous_state = onehot_to_loc(self.env_reset(init=0, verbose=True),grid_size)

        # run the episode until discovered the reward
        N_steps = 0
        total_r = 0
        s_macro_max = self.micro_to_macro[np.where(self.C > 0)[0][0]] #last square in grid
        # print('smax',s_macro_max)

        if time_episode == True:
            ckpt_time = time.time()
        
        while True:
            s_macro = self.micro_to_macro[self.env.get_state_idx()]
            N = self.n_clust
            V_macro = self.M_macro @ self.C_macro
            # print('vm',V_macro)
            s_adj = []
            for action in range(self.n_macro_actions):
                s_adj.append(onehot_to_idx(self.B_macro[:,:,action] @ np.eye(N)[s_macro]))
            V_adj = [V_macro[s] for s in s_adj]
            # print('vadj',V_adj)
            # print('sadj',s_adj)

            ba_gen = (ele for ele in np.argsort(V_adj)[::-1])
            best_action = next(ba_gen)
            # print('ba',s_macro,best_action)
            s_macro_new = s_adj[best_action]
            # print(s_macro_new)
            
            while s_macro == s_macro_new:
                try:
                    best_action = next(ba_gen)
                    s_macro_new = s_adj[best_action]
                except StopIteration:
                    break
            if s_macro == s_macro_new: break #There were no macro actions available for that state, so we move to planning in lower level.
            N_steps_action, total_r_action = self.execute_macro_action(s_macro,s_macro_new)
            N_steps += 1 #N_steps_action
            total_r += total_r_action
            if s_macro_new != self.micro_to_macro[self.env.get_state_idx()]: break # Did not actually reach the successor macro state
            s_macro = s_macro_new
            print('ms: ',s_macro)
            print('--\n')
            if s_macro == s_macro_max or N_steps > 100 : 
                break

        if time_episode == True:
            ckpt_time2 = time.time()

        goal = idx_to_onehot(self.goal_idx, grid_size)
        V = self.M @ self.C
        # print(np.array(V).reshape(grid_size,grid_size).T)
        
        print('Current state',self.env.get_state_loc())
        
        while (self.s != goal).any():   
            s_left = self.B[:,:,0] @ self.s
            s_right = self.B[:,:,1] @ self.s
            s_up = self.B[:,:,2] @ self.s
            s_down = self.B[:,:,3] @ self.s
        
            V_left = V[onehot_to_idx(s_left)]
            V_right = V[onehot_to_idx(s_right)]
            V_up = V[onehot_to_idx(s_up)]
            V_down = V[onehot_to_idx(s_down)]
            
            # print([V_left, V_right, V_up, V_down])
            ba_gen = (ele for ele in np.argsort([V_left, V_right, V_up, V_down])[::-1])
            best_action = next(ba_gen)
            # so now we actually take the next action
            s_new = self.env.step(best_action)
            while (self.s == s_new).all():
                best_action = next(ba_gen)
                s_new = self.env.step(best_action)
            # print(best_action,end=' ')

            self.s = s_new 
            self.s_array.append(self.s)
            self.a_array.append(best_action)
            r = self.C[onehot_to_idx(self.s)]
            total_r += r
            print('s:',self.env.get_state_loc())
            N_steps +=1
            if N_steps > 3*self.env.grid_size:
                break
        
        end_state = self.env.get_state_loc()
        print('End state',end_state)

        if time_episode == True:
            total_time = (time.time() - ckpt_time2) + (ckpt_time - start_time)
            return N_steps, total_r, total_time, end_state
        return N_steps, total_r, 0, end_state



def SR_performance_Hierarchy(args):
    SR_steps = []
    SR_rewards = []
    SR_times = []

    grid_size = args.grid_size
    print('Number of macro states: ',args.n_macro)
 

    for n in range(args.n_runs):
        print('x'*20)
        print(f"Run {n}")
        print('x'*20)
        SR_step = []
        SR_reward = []
        SR_time = []

        grid_env = SR_Gridworld(grid_size) 
        grid_env.set_walls(args.walls)

        # SR agent
        inverse_factor = 1
        if grid_size > 7:
            inverse_factor = 4
        agent = SR_Agent_Hierarchy(grid_env, inverse_factor=inverse_factor,n_clust = args.n_macro, 
                                init_loc = args.init_loc, goal_loc = args.goal_loc, goal_val=args.goal_val,
                                learn_likelikood=True)     

        for num in range(len(args.episodes)):
            if num == 0:
                num_episodes = args.episodes[num]
            else:
                num_episodes = args.episodes[num] - args.episodes[num-1]
            print()
            print('+'*25)
            print(f'{args.episodes[num]} training episodes')
            print('+'*25)
            print()
           
            agent.learn_env_likelikood(num_episodes)
            N_steps, total_r,total_time,_ = agent.run_episode()
            # agent.show_actions()
            agent.visualize_policy()
            # agent.show_video()
            
            SR_step.append(deepcopy(N_steps))
            SR_reward.append(deepcopy(total_r))
            SR_time.append(deepcopy(total_time))
            


        SR_step = np.array(SR_step)
        SR_reward= np.array(SR_reward)
        SR_time = np.array(SR_time)

        SR_steps.append(SR_step)
        SR_rewards.append(SR_reward)
        SR_times.append(SR_time)

    SR_steps = np.array(SR_steps)
    SR_rewards= np.array(SR_rewards)
    SR_times = np.array(SR_times)
    
    return SR_steps, SR_rewards, SR_times

    
if __name__ == '__main__':
    grid_size = 9
    n_macro = 4
    init_loc = (0,0)
    goal_loc = (grid_size-1,grid_size-1)
    nruns = 1
    eps = [1000,1200]
    goal_val = 100
    WALLS = [(1,x) for x in range(grid_size//2+2)] + \
            [(3,x) for x in range(grid_size//2-2,grid_size)] +\
            [(5,x) for x in range(grid_size//2+2)] + \
            [(7,x) for x in range(grid_size//2-2,grid_size)]
            
    WALLS = [(4,x) for x in range(grid_size) if x not in [2,6]] + \
            [(x,4) for x in range(grid_size) if x not in [2,6]]

    # WALLS = [(1,x) for x in range(grid_size-1)] + \
    #         [(3,x) for x in range(1,grid_size)]
    
    parser = argparse.ArgumentParser(description="Arguments for hierarchical model")
    parser.add_argument("grid_size", nargs='?',type=int, default=grid_size, help="Grid size of environment")
    parser.add_argument("n_macro", nargs='?',type=int, default=n_macro, help="Number of macro states")
    parser.add_argument("init_loc", nargs='?',type=int, default=init_loc, help="Initial location of agent")
    parser.add_argument("goal_loc", nargs='?',type=int, default=goal_loc, help="Goal location of agent")
    parser.add_argument("goal_val", nargs='?',type=int, default=goal_val, help="Goal value of agent")
    parser.add_argument("n_runs", nargs='?', type=int, default=nruns, help="Number of runs for the experiment")
    parser.add_argument("walls", nargs='?', type=list, default=WALLS, help="Range of walls")
    parser.add_argument("episodes", nargs='?', type=tuple, default=eps, help="Range of number of episodes")
    args = parser.parse_args()
    
    print('Hierarchical Model')
    print('*'*50)
    SR_steps, SR_rewards, SR_times= SR_performance_Hierarchy(args)
    print('*'*50)
    
    
    if not os.path.exists("data/"):
        os.makedirs("data/")
        
    np.save("data/SR_steps.npy", SR_steps)
    np.save("data/SR_rewards.npy", SR_rewards)
    np.save("data/SR_times.npy", SR_times)

